apiVersion : apps/v1
kind: Deployment
metadata:
  name: qacomerssia 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qacomerssia
  template:
    metadata:
      labels:
        app: qacomerssia 
    spec:
      containers:
        - name: qacomerssia 
          image: assaabloy.azurecr.io/qacomerssia
          ports:
          - containerPort: 8080

          env:
            - name: QACOMERSSIA_APP_PROFILE
              valueFrom:
                configMapKeyRef:
                  name: qacomerssia-config
                  key: QACOMERSSIA_APP_PROFILE

            - name: QACOMERSSIA_APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: qacomerssia-config
                  key: QACOMERSSIA_APP_PORT

            - name: QACOMERSSIA_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: qacomerssia-config
                  key: QACOMERSSIA_DB_HOST

            - name: QACOMERSSIA_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: qacomerssia-config
                  key: QACOMERSSIA_DB_NAME

            - name: QACOMERSSIA_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: qacomerssia-config
                  key: QACOMERSSIA_DB_PORT

            - name: QACOMERSSIA_DB_TIMEZONE
              valueFrom:
                configMapKeyRef:
                  name: qacomerssia-config
                  key: QACOMERSSIA_DB_TIMEZONE

            - name: QACOMERSSIA_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: qacomerssia-secret
                  key: QACOMERSSIA_DB_PASSWORD

            - name: QACOMERSSIA_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: qacomerssia-secret
                  key: QACOMERSSIA_DB_USERNAME
      imagePullSecrets:
        - name: acr-secret